### ISSUE TITLE
[Backlog WG] Question about IoT Data Transfer Activation

### ISSUE THREAD

**Issue by jgarciahospital** [camaraproject/DedicatedNetworks#13]
During last Backlog meeting, new proposal of IoT Data Transfer Activation was presented

- Issue: [143](https://github.com/camaraproject/APIBacklog/issues/143)
- PR of [template](https://github.com/camaraproject/APIBacklog/blob/858f2fb7500dd31b7b893ca2de6868d6d4749540/documentation/API%20proposals/APIproposal_IoT_Data_Transfer_Activation_TIM.md)

Question was raised about posible overlap with Dedicated Networks Scope, as targeted to define an API for booking resources for a non-warranted connection for IoT, group of many devices at once, during a certain period.

Dedicated Network group is required to provide feedback.

**Comment by tlohmar** [comment]
Several aspects resonate, like negotiating a time window and a maximum aggregate bitrate. The offered resources and capabilities for _off-peak_ and _peak_ hours seem to be more on the the Network Provider side, e.g. there can be different reasons for rejecting a request. 

The slogans "background data transfers" and "non-urgent updates or downloads" could be translated to a need for "connectivity with a qos profile, suitable for a background data transfer".

I dont see a reason, why the dedicated network API cannot be used for a background data transfer use-case. However, the dedicated network API design is still in an early phase and there might be some use-case specific requirements.

**Comment by jgarciahospital** [comment]
Closing as discussed in #14
